export const routeData = {
  "1": {
    name: "Route 1 - Prince School",
    stops: [
      { name: "PRINCE SCHOOL", time: "7:20" },
      { name: "MADIPAKKAM KOOT ROAD", time: "7:22" },
      { name: "MOOVARASAMPET KULAM", time: "7:24" },
      { name: "EZHURAMMAN KOIL", time: "7:26" },
      { name: "JK MAHAL", time: "7:28" },
      { name: "BHUVANESESWARI AMMAN TEMPLE (NANGANALLUR)", time: "7:30" },
      { name: "RENGA THEATRE", time: "7:32" },
      { name: "INDEPENDENCE DAY PARK", time: "7:34" },
      { name: "ROJA MEDICAL SHOP, NANGANALLUR", time: "7:36" },
      { name: "PILLAIYAR TEMPLE, NANGANALLUR", time: "7:38" },
      { name: "KARUMARI AMMAN KOVIL", time: "7:40" },
      { name: "JEYALAKSHMI THEATRE", time: "7:42" },
      { name: "MOUNT RAILWAY STATION", time: "7:44" },
      { name: "NGO COLONY", time: "7:46" },
      { name: "KAKKAN BRIDGE", time: "7:48" },
      { name: "BRINDAVANAM NAGAR", time: "7:50" },
      { name: "PRIME CARE HOSPITAL", time: "7:52" },
      { name: "PUZHUTHIVAKKAM POLICE BOOTH", time: "7:54" },
      { name: "PALLIKARANAI POLICE BOOTH", time: "8:15" },
      { name: "PALLIKARANAI OIL MILL", time: "8:20" },
      { name: "MEDAVAKKAM VIJAYANAGARAM", time: "8:25" },
      { name: "COLLEGE", time: "" },
    ],
  },
  "2": {
    name: "Route 2 - Perungudi",
    stops: [
      { name: "SRP TOOLS", time: "7:30" },
      { name: "PERUNGUDI", time: "7:33" },
      { name: "KANTHANCHAVADI POORVIKA MOBILES", time: "7:35" },
      { name: "TARAMANI", time: "7:40" },
      { name: "TCS", time: "7:43" },
      { name: "BABY NAGAR", time: "7:45" },
      { name: "TANSI NAGAR", time: "7:48" },
      { name: "VELACHERY VIJAYANAGAR BUS STOP", time: "7:53" },
      { name: "A2B - 200 FEET RADIAL ROAD", time: "8:05" },
      { name: "ZONE HOTEL – VINAYAGAPURAM (S KOLATHUR)", time: "8:10" },
      { name: "RANI MAHAL", time: "8:13" },
      { name: "VEERAMANI NAGAR", time: "8:15" },
      { name: "VADAKUPATTU", time: "8:18" },
      { name: "VELLAKAL", time: "8:20" },
      { name: "BHEL NAGAR (Sri Baktha Anjaneya Temple)", time: "8:25" },
      { name: "COLLEGE", time: "" },
    ],
  },
  // Add more routes as needed
};
